apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cleanup-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cleanup-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
  selector:
    matchLabels:
      {{- include "cleanup-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cleanup-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cleanup-operator.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.podSecurityContext.runAsGroup }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        fsGroupChangePolicy: {{ .Values.podSecurityContext.fsGroupChangePolicy }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          capabilities:
            drop:
              - ALL
        env:
        - name: CONFIG_PATH
          value: "/etc/config/config.yaml"
        - name: CLEANUP_NAMESPACES
          value: {{ join "," .Values.config.namespaces | quote }}
        - name: CLEANUP_INTERVAL
          value: {{ .Values.config.cleanupInterval | quote }}
        - name: DRY_RUN
          value: {{ .Values.config.dryRun | quote }}
        - name: KOPF_STANDALONE
          value: "true"
        - name: KOPF_NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.config.logLevel | quote }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "cleanup-operator.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}