{{- if .Values.crd.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cleanups.resources.muntashir.com
  labels:
    {{- include "cleanup-operator.labels" . | nindent 4 }}
spec:
  group: resources.muntashir.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              namespaces:
                type: array
                items:
                  type: string
              unusedThresholdHours:
                type: integer
              dryRun:
                type: boolean
              force:
                type: boolean
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.state
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: cleanups
    singular: cleanup
    kind: Cleanup
    shortNames:
    - clnp
{{- end }}