# Default values for cleanup-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: muntashir/cleanup-operator
  tag: v4
  pullPolicy: IfNotPresent

# Resource limits for the operator
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Security context for the pod and containers
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Pod security context
podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"

# Operator configuration
config:
  # Namespaces to scan for cleanup
  namespaces:
    - default
    - production
    - staging
    - development
  
  # Cleanup interval in seconds (default: 1 hour)
  cleanupInterval: 3600
  
  # Minimum age of resources to consider for cleanup (in hours)
  unusedThresholdHours: 2
  
  # Set to true to run in dry-run mode (won't actually delete resources)
  dryRun: true
  
  # Patterns for resources to exclude from cleanup
  excludePatterns:
    - "kube-*"
    - "default-token-*"
  
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  logLevel: "INFO"

# Deployment configuration
deployment:
  replicas: 1
  strategy:
    type: Recreate

# Service account configuration
serviceAccount:
  create: true
  name: "cleanup-operator"
  annotations: {}

# Custom Resource Definition configuration
crd:
  create: true

# RBAC configuration
rbac:
  create: true

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 0

# Create a default Cleanup CR instance
defaultCleanupCR:
  create: true
  name: "default-cleanup"
  spec:
    namespaces:
      - default
      - production
      - staging
    unusedThresholdHours: 2
    dryRun: true

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}